language: python
python:
  - "2.7"
install:
  - pip install --upgrade pip
  - pip --version
  - pip install --egg SCons
  - pip install .
  - pip install -r requirements.txt -r test-requirements.txt
script: nosetests
