sudo: false
language: python
python: 
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

cache: false

services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

install:
  - pip install --upgrade pip
  - pip install tox-travis

script:
  - export DATABASE_URI="mysql://root:@127.0.0.1:/test"
  - tox
