name: tests

on:
  push:
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Flake8
        run: |
          tox -e pep8
  tests:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.10", "3.12", "3.13"]
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
          MARIADB_DATABASE: radatabase
          MARIADB_USERf: root
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Unit tests
        run: |
          tox -e ${{ matrix.python-version }}
      - name: Functional tests
        run: |
          tox -e ${{ matrix.python-version }}-functional
